name: Deploy and Keep Alive

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install    # Hapus cd items-dat-api
          
      - name: Start API
        run: |
          node index.js &   # Hapus cd items-dat-api
          sleep 5
          
      - name: Keep alive ping
        run: curl http://localhost:3000/health || exit 0
